version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres
    restart: always
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: usernet
      POSTGRES_PASSWORD: dbmeu
      POSTGRES_DB: streamer

volumes:
  postgres-disk: